
// export type Properties = 'string' | 'markdown' | 'url' | 'email' | 'phone' | 'date' | 'time' | 'datetime' | 'timestamp' | 'number' | 'integer' | 'currency' | 'boolean' | 'object'

export const propertyTypeMappings = {
  string: 'string',
  markdown: 'string',
  url: '\`https://${string}\`',
  email: '\`${string}@${string}\`',
  phone: 'string',
}

export const generateJavascript = graph => `// Generated by GraphDL
${graph.nouns.map(noun => `
export type ${noun._id} = {
  ${Object.entries(noun).map(([property, propertyType]) => `${property}: ${propertyTypeMappings[propertyType] ?? 'string'}`)}
}
`)}
`